# -*- coding: utf-8 -*-
"""Interpolated n-gram model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xM1FZ01KWy-IQAsIcIMoAlKW5yChpNm
"""

pip install sentencepiece numpy tqdm

import os
import urllib.request
import zipfile
import sentencepiece as spm
import collections
import numpy as np
from tqdm import tqdm
from math import log

def load_text8_data(max_train_words=100_000, max_val_words=10_000):
    print("Loading Text8 dataset...")

    if not os.path.exists('text8'):
        print("Downloading Text8 dataset...")
        url = 'http://mattmahoney.net/dc/text8.zip'
        urllib.request.urlretrieve(url, 'text8.zip')

        print("Extracting Text8 dataset...")
        with zipfile.ZipFile('text8.zip', 'r') as zip_ref:
            zip_ref.extractall('.')

        os.remove('text8.zip')

    with open('text8', 'r') as f:
        text = f.read()

    words = text.split()

    train_words = words[:max_train_words]
    val_words = words[max_train_words:max_train_words + max_val_words]

    train_text = ' '.join(train_words)
    val_text = ' '.join(val_words)

    print(f"Training word count: {len(train_words)}")
    print(f"Validation word count: {len(val_words)}")

    return train_text, val_text

def train_sentencepiece_model(input_text, model_prefix="text8_sp", vocab_size=8000):
    input_file = "spm_input.txt"

    # ✅ Make sure we write valid non-empty lines
    with open(input_file, "w", encoding="utf-8") as f:
        # Break text into ~1k chunks (simulate sentences)
        chunk_size = 1000
        for i in range(0, len(input_text), chunk_size):
            line = input_text[i:i+chunk_size].strip().replace("\n", " ")
            if line:
                f.write(line + "\n")  # each line is a sentence

    # ✅ Confirm file is not empty
    assert os.path.getsize(input_file) > 0, "SPM input file is empty!"

    # Train SentencePiece
    spm.SentencePieceTrainer.Train(
        input=input_file,
        model_prefix=model_prefix,
        vocab_size=vocab_size,
        model_type='bpe',
        bos_id=-1,
        eos_id=-1
    )

def tokenize_text(text, sp_model_path):
    sp = spm.SentencePieceProcessor(model_file=sp_model_path)
    tokens = sp.encode(text, out_type=str)
    return tokens, sp

def build_ngram_counts(tokens):
    unigram = collections.Counter()
    bigram = collections.Counter()
    trigram = collections.Counter()

    for i in range(2, len(tokens)):
        w1, w2, w3 = tokens[i-2], tokens[i-1], tokens[i]
        unigram[w3] += 1
        bigram[(w2, w3)] += 1
        trigram[(w1, w2, w3)] += 1

    return unigram, bigram, trigram

def get_context_bins(bigram_counts, num_bins=10):
    freqs = np.array(list(bigram_counts.values()))
    bins = np.percentile(freqs, np.linspace(0, 100, num_bins+1))
    bins[-1] += 1e-5  # Avoid edge issues
    return bins

def assign_bin(context, bigram_counts, bins):
    freq = bigram_counts.get(context, 0)
    for i in range(len(bins) - 1):
        if bins[i] <= freq < bins[i+1]:
            return i
    return len(bins) - 2

def em_train_adaptive_weights(val_tokens, unigram, bigram, trigram, bins, bigram_counts,
                              num_bins=10, num_iters=5, vocab_size=8000):
    # Each bin has its own alpha1, alpha2, alpha3
    weights = np.full((num_bins, 3), 1/3)

    for _ in range(num_iters):
        numer = np.zeros((num_bins, 3))
        denom = np.zeros(num_bins)

        for i in range(2, len(val_tokens)):
            w1, w2, w3 = val_tokens[i-2], val_tokens[i-1], val_tokens[i]

            u_prob = unigram[w3] / sum(unigram.values()) if unigram[w3] else 1 / vocab_size
            b_prob = bigram[(w2, w3)] / unigram[w2] if unigram[w2] else u_prob
            t_prob = trigram[(w1, w2, w3)] / bigram[(w1, w2)] if bigram[(w1, w2)] else b_prob

            bin_id = assign_bin((w1, w2), bigram, bins)
            α = weights[bin_id]
            total = α[0]*u_prob + α[1]*b_prob + α[2]*t_prob
            if total == 0:
                continue

            numer[bin_id][0] += α[0]*u_prob / total
            numer[bin_id][1] += α[1]*b_prob / total
            numer[bin_id][2] += α[2]*t_prob / total
            denom[bin_id] += 1

        for b in range(num_bins):
            if denom[b] > 0:
                weights[b] = numer[b] / denom[b]
            else:
                weights[b] = [1/3, 1/3, 1/3]

    return weights

def predict_next_token(context, sp, weights, unigram, bigram, trigram, bins, vocab_size=8000):
    w1, w2 = context
    vocab = [sp.id_to_piece(i) for i in range(sp.get_piece_size())]
    probs = {}
    bin_id = assign_bin((w1, w2), bigram, bins)
    α = weights[bin_id]

    for token in vocab:
        u_prob = unigram[token] / sum(unigram.values()) if unigram[token] else 1 / vocab_size
        b_prob = bigram[(w2, token)] / unigram[w2] if unigram[w2] else u_prob
        t_prob = trigram[(w1, w2, token)] / bigram[(w1, w2)] if bigram[(w1, w2)] else b_prob
        probs[token] = α[0]*u_prob + α[1]*b_prob + α[2]*t_prob

    return sorted(probs.items(), key=lambda x: x[1], reverse=True)[:5]

if __name__ == "__main__":
    train_text, val_text = load_text8_data(max_train_words=100_000, max_val_words=10_000)
    train_sentencepiece_model(train_text)

    train_tokens, sp = tokenize_text(train_text, "text8_sp.model")
    val_tokens, _ = tokenize_text(val_text, "text8_sp.model")

    print("Building n-gram counts...")
    unigram, bigram, trigram = build_ngram_counts(train_tokens)
    bigram_counts = collections.Counter()
    for (w1, w2, _), _ in trigram.items():
        bigram_counts[(w1, w2)] += 1

    print("Binning contexts...")
    bins = get_context_bins(bigram_counts)

    print("Running EM for adaptive interpolation...")
    weights = em_train_adaptive_weights(val_tokens, unigram, bigram, trigram, bins, bigram_counts)

    # Prediction test
    input_text = "king sit"
    example_tokens = sp.encode(input_text, out_type=str)

    if len(example_tokens) >= 2:
        context = example_tokens[-2:]
        print(f"\nContext: {' '.join(context)}")
        predictions = predict_next_token(context, sp, weights, unigram, bigram, trigram, bins)
        print("Top 5 predictions:")
        for tok, prob in predictions:
            print(f"→ {tok} ({prob:.5f})")
    else:
        print("Need at least 2 tokens for trigram context.")

