# -*- coding: utf-8 -*-
"""Trigram statistical model implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzryxPPnMW_O4OGzz62PyC9qteRzdiF7
"""

text = """
the cat sat on the mat and the dog ran in the park
the quick brown fox jumps over the lazy dog
the dog chased the cat around the tree
the mat was hard and the cat liked it
the park had many trees and the dog loved to run there
the fox was clever and the dog was playful
the lazy cat slept on the mat all day
the brown fox ran quickly through the park
""".lower()

words = text.replace('.', '').replace('\n', ' ').split()
vocab = sorted(set(words))

stoi = {w: i+1 for i, w in enumerate(vocab)}  # index 0 reserved for special token (e.g. start/end)
stoi['.'] = 0
itos = {i: w for w, i in stoi.items()}

vocab_size = len(stoi)

import torch
import matplotlib.pyplot as plt

#counting trigrams
C = torch.zeros((vocab_size, vocab_size, vocab_size), dtype=torch.int32)

# Pad each sentence with start (.) and end (.) tokens
sentences = text.strip().split('\n')
for sentence in sentences:
    tokens = ['.'] + sentence.strip().replace('.', '').split() + ['.']
    for w1, w2, w3 in zip(tokens, tokens[1:], tokens[2:]):
        ix1 = stoi[w1]
        ix2 = stoi[w2]
        ix3 = stoi[w3]
        C[ix1, ix2, ix3] += 1

P = C.float()
P /= P.sum(dim=2, keepdim=True)

# Step 5: Generate new word sequences using trigram probabilities
import random

def generate_trigram_sentence(max_words=15):
    out = ['.', '.']
    for _ in range(max_words):
        ix1 = stoi[out[-2]]
        ix2 = stoi[out[-1]]
        probs = P[ix1, ix2]
        if torch.isnan(probs).any():  # Fallback in case of no data for pair
            probs = torch.ones(vocab_size) / vocab_size
        ix3 = torch.multinomial(probs, num_samples=1).item()
        word = itos[ix3]
        if word == '.':
            break
        out.append(word)
    return ' '.join(out[2:])  # skip starting '. .'

for _ in range(5):
    print(generate_trigram_sentence())

import math

log_likelihood = 0.0
n = 0  # number of valid trigrams

for sentence in text.strip().split('\n'):
    tokens = ['.'] + sentence.strip().replace('.', '').split() + ['.']
    for w1, w2, w3 in zip(tokens, tokens[1:], tokens[2:]):
        if w1 in stoi and w2 in stoi and w3 in stoi:
            ix1 = stoi[w1]
            ix2 = stoi[w2]
            ix3 = stoi[w3]
            prob = P[ix1, ix2, ix3].item()

            if prob > 0:
                log_likelihood += -math.log(prob)
            else:
                log_likelihood += -math.log(1e-9)  # small value to avoid -inf

            n += 1

average_log_loss = log_likelihood / n
print(f'Average Log Loss: {average_log_loss:.4f}')